### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by wmrenr** [zhangxiaoyu11/OmiVAE#1]
Is the data in the data folder all preprocessed? In the data folder, the file path in some codes cannot be found

**Comment by zhangxiaoyu11** [comment]
Hi, thanks for your interests. The OmiVAE repo is currently deprecated. All of the functionalities have been merged into the OmiEmbed repo (https://github.com/zhangxiaoyu11/OmiEmbed).

**Comment by wmrenr** [comment]
oh,thanks!If any questions,I will ask for you!
